// <auto-generated />
using System;
using LedgerGuard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LedgerGuard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerGuardDbContext))]
    [Migration("20260826033200_AddFinancialEntities")]
    partial class AddFinancialEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LedgerGuard.Domain.Aggregates.AccountAggregate.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("owner_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_balance_non_negative", "balance_amount >= 0");
                        });
                });

            modelBuilder.Entity("LedgerGuard.Domain.Aggregates.LedgerAggregate.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("ledger_transactions", (string)null);
                });

            modelBuilder.Entity("LedgerGuard.Domain.Aggregates.TransferAggregate.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_account_id");

                    b.Property<Guid>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_account_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("LedgerTransactionId")
                        .IsUnique();

                    b.HasIndex("SourceAccountId");

                    b.ToTable("transfers", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfers_amount_positive", "amount_value > 0");

                            t.HasCheckConstraint("ck_transfers_different_accounts", "source_account_id <> destination_account_id");
                        });
                });

            modelBuilder.Entity("LedgerGuard.Domain.Aggregates.TransferReversalAggregate.TransferReversal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id");

                    b.HasIndex("LedgerTransactionId")
                        .IsUnique();

                    b.HasIndex("TransferId")
                        .IsUnique();

                    b.HasIndex("Status", "RequestedAt");

                    b.ToTable("transfer_reversals", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfer_reversals_completed_after_requested", "completed_at IS NULL OR completed_at >= requested_at");
                        });
                });

            modelBuilder.Entity("LedgerGuard.Domain.Aggregates.AccountAggregate.Account", b =>
                {
                    b.OwnsOne("LedgerGuard.Domain.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(20, 2)
                                .HasColumnType("numeric(20,2)")
                                .HasColumnName("balance_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("balance_currency");

                            b1.HasKey("AccountId");

                            b1.ToTable("accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();
                });

            modelBuilder.Entity("LedgerGuard.Domain.Aggregates.LedgerAggregate.LedgerTransaction", b =>
                {
                    b.OwnsMany("LedgerGuard.Domain.Aggregates.LedgerAggregate.LedgerEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("account_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("entry_type");

                            b1.Property<Guid>("ledger_transaction_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("ledger_transaction_id");

                            b1.ToTable("ledger_entries", (string)null);

                            b1.HasOne("LedgerGuard.Domain.Aggregates.AccountAggregate.Account", null)
                                .WithMany()
                                .HasForeignKey("AccountId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ledger_transaction_id");

                            b1.OwnsOne("LedgerGuard.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("LedgerEntryid")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(20, 2)
                                        .HasColumnType("numeric(20,2)")
                                        .HasColumnName("amount_value");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("amount_currency");

                                    b2.HasKey("LedgerEntryid");

                                    b2.ToTable("ledger_entries");

                                    b2.WithOwner()
                                        .HasForeignKey("LedgerEntryid");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("LedgerGuard.Domain.Aggregates.TransferAggregate.Transfer", b =>
                {
                    b.HasOne("LedgerGuard.Domain.Aggregates.AccountAggregate.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LedgerGuard.Domain.Aggregates.LedgerAggregate.LedgerTransaction", null)
                        .WithMany()
                        .HasForeignKey("LedgerTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LedgerGuard.Domain.Aggregates.AccountAggregate.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LedgerGuard.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransferId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(20, 2)
                                .HasColumnType("numeric(20,2)")
                                .HasColumnName("amount_value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("TransferId");

                            b1.ToTable("transfers");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("LedgerGuard.Domain.Aggregates.TransferReversalAggregate.TransferReversal", b =>
                {
                    b.HasOne("LedgerGuard.Domain.Aggregates.LedgerAggregate.LedgerTransaction", null)
                        .WithMany()
                        .HasForeignKey("LedgerTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LedgerGuard.Domain.Aggregates.TransferAggregate.Transfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
